-- UberMap map data, rewritten by /um edit.
--
-- 'groups' holds the overview tiers, drawn in order so later groups land on top
-- of earlier ones; their names are what the point rows below refer to by 'group'.
-- 'points' holds the zone markers, drawn once the view is zoomed past the
-- overview.  'time' tags which map a marker belongs to.
local POINT_SIZE = 30;

return {
    groups = {
        { name = "Nations", icons = {
            { file = "SandOria.jpg", x = 1075, y =  971, label = "San d'Oria", time = "present" },
            { file = "Bastok.jpg", x = 1340, y = 1886, label = "Bastok", time = "present" },
            { file = "Jeuno.jpg", x = 1737, y = 1207, label = "Jeuno", time = "present" },
            { file = "Windurst.jpg", x = 2115, y = 1986, label = "Windurst", time = "present" },
            { file = "AhtUrhgan.jpg", x = 5009, y = 1796, label = "Aht Urhgan", time = "present" },
            { file = "SandOria.jpg", x = 1419, y = 1299, label = "San d'Oria", time = "past" },
            { file = "Bastok.jpg", x = 1774, y = 2511, label = "Bastok", time = "past" },
            { file = "Jeuno.jpg", x = 2297, y = 1619, label = "Jeuno", time = "past" },
            { file = "Windurst.jpg", x = 2797, y = 2647, label = "Windurst", time = "past" },
            { file = "Beastmen.jpg", x = 3206, y = 1849, label = "Yagudo Theomilitary", size = POINT_SIZE, time = "past" },
            { file = "Beastmen.jpg", x = 1227, y =  705, label = "Dark Kindred", size = POINT_SIZE, time = "past" },
            { file = "Beastmen.jpg", x = 1646, y = 1674, label = "Orcish Hosts", size = POINT_SIZE, time = "past" },
            { file = "Beastmen.jpg", x = 1902, y = 2066, label = "Quadav Shieldwarriors", size = POINT_SIZE, time = "past" },
        } },
        { name = "Regions", icons = {
            { file = "Point_0.png", x = 1000, y =  695, label = "Valdeaunia", border = false, size = POINT_SIZE, time = "present" },
            { file = "Point_0.png", x = 1538, y =  837, label = "Fauregandi", border = false, size = POINT_SIZE, time = "present" },
            { file = "Point_0.png", x = 1473, y =  941, label = "Norvallen", border = false, size = POINT_SIZE, time = "present" },
            { file = "Point_0.png", x = 1899, y =  976, label = "Qufim", border = false, size = POINT_SIZE, time = "present" },
            { file = "Point_0.png", x = 2029, y =  777, label = "Tu'Lia", border = false, size = POINT_SIZE, time = "present" },
            { file = "Point_0.png", x = 1074, y = 1089, label = "Ronfaure", border = false, size = POINT_SIZE, time = "present" },
            { file = "Point_0.png", x =  431, y = 1415, label = "Tavnazian Archipelago", border = false, size = POINT_SIZE, time = "present" },
            { file = "Point_0.png", x =  597, y = 1574, label = "Vollbow", border = false, size = POINT_SIZE, time = "present" },
            { file = "Point_0.png", x = 1105, y = 1459, label = "Zulkheim", border = false, size = POINT_SIZE, time = "present" },
            { file = "Point_0.png", x =  533, y = 2134, label = "Kuzotz", border = false, size = POINT_SIZE, time = "present" },
            { file = "Point_0.png", x = 1003, y = 1898, label = "Gustaberg", border = false, size = POINT_SIZE, time = "present" },
            { file = "Point_0.png", x = 1488, y = 1787, label = "Movalpolos", border = false, size = POINT_SIZE, time = "present" },
            { file = "Point_0.png", x = 1530, y = 1412, label = "Derfland", border = false, size = POINT_SIZE, time = "present" },
            { file = "Point_0.png", x = 2184, y = 1348, label = "Aragoneu", border = false, size = POINT_SIZE, time = "present" },
            { file = "Point_0.png", x = 2538, y = 1283, label = "Li'Telor", border = false, size = POINT_SIZE, time = "present" },
            { file = "Point_0.png", x = 2295, y = 1577, label = "Kolshushu", border = false, size = POINT_SIZE, time = "present" },
            { file = "Point_0.png", x = 2180, y = 1780, label = "Sarutabaruta", border = false, size = POINT_SIZE, time = "present" },
            { file = "Point_0.png", x = 2445, y = 2364, label = "Elshimo Lowlands", border = false, size = POINT_SIZE, time = "present" },
            { file = "Point_0.png", x = 2669, y = 2394, label = "Elshimo Uplands", border = false, size = POINT_SIZE, time = "present" },
            { file = "Point_0.png", x = 3863, y =  861, label = "Arrapago Islands", border = false, size = POINT_SIZE, time = "present" },
            { file = "Point_0.png", x = 3981, y = 1343, label = "Ruins of Alzadaal", border = false, size = POINT_SIZE, time = "present" },
            { file = "Point_0.png", x = 4158, y = 1713, label = "Halvung Territory", border = false, size = POINT_SIZE, time = "present" },
            { file = "Point_0.png", x = 4072, y = 2344, label = "Mamool Ja Savagelands", border = false, size = POINT_SIZE, time = "present" },
            { file = "Point_0.png", x = 4703, y = 1852, label = "West Aht Urhgan", border = false, size = POINT_SIZE, time = "present" },
        } },
    },
    points = {
        { file = "Point_0.png", x = 1019, y = 1803, label = "North Gustaberg", border = false, size = POINT_SIZE, group = "Gustaberg", time = "present" },
        { file = "Point_0.png", x = 1059, y = 1987, label = "Dangruf Wadi", border = false, size = POINT_SIZE, group = "Gustaberg", time = "present" },
        { file = "Point_0.png", x = 1208, y = 2046, label = "South Gustaberg", border = false, size = POINT_SIZE, group = "Gustaberg", time = "present" },
        { file = "Point_0.png", x = 1272, y = 1971, label = "Zeruhn Mines", border = false, size = POINT_SIZE, group = "Gustaberg", time = "present" },
        { file = "Point_0.png", x = 1434, y = 1707, label = "Palborough Mines", border = false, size = POINT_SIZE, group = "Gustaberg", time = "present" },
        { file = "Point_0.png", x = 1591, y = 1295, label = "Rolanberry Fields", border = false, size = POINT_SIZE, group = "Derfland", time = "present" },
        { file = "Point_0.png", x = 1669, y = 1307, label = "Crawlers' Nest", border = false, size = POINT_SIZE, group = "Derfland", time = "present" },
        { file = "Point_0.png", x = 1418, y = 1501, label = "Qulun Dome", border = false, size = POINT_SIZE, group = "Derfland", time = "present" },
        { file = "Point_0.png", x = 1348, y = 1451, label = "Pashhow Marshlands", border = false, size = POINT_SIZE, group = "Derfland", time = "present" },
        { file = "Point_0.png", x = 1418, y = 1433, label = "Beadeaux", border = false, size = POINT_SIZE, group = "Derfland", time = "present" },
        { file = "Point_0.png", x =  547, y = 1633, label = "Cape Teriggan", border = false, size = POINT_SIZE, group = "Vollbow", time = "present" },
        { file = "Point_0.png", x =  618, y = 1670, label = "Valley of Sorrows", border = false, size = POINT_SIZE, group = "Vollbow", time = "present" },
        { file = "Point_0.png", x =  682, y = 1418, label = "Gustav Tunnel", border = false, size = POINT_SIZE, group = "Vollbow", time = "present" },
        { file = "Point_0.png", x =  541, y = 1477, label = "Cloister of Gales", border = false, size = POINT_SIZE, group = "Vollbow", time = "present" },
        { file = "Point_0.png", x = 1277, y =  699, label = "The Shrouded Maw", border = false, size = POINT_SIZE, group = "Fauregandi", time = "present" },
        { file = "Point_0.png", x = 1296, y =  801, label = "Ranguemont Pass", border = false, size = POINT_SIZE, group = "Fauregandi", time = "present" },
        { file = "Point_0.png", x = 1340, y =  636, label = "Pso'Xja", border = false, size = POINT_SIZE, group = "Fauregandi", time = "present" },
        { file = "Point_0.png", x = 1427, y =  645, label = "Beaucedine Glacier", border = false, size = POINT_SIZE, group = "Fauregandi", time = "present" },
        { file = "Point_0.png", x = 1538, y =  632, label = "Fei'Yin", border = false, size = POINT_SIZE, group = "Fauregandi", time = "present" },
        { file = "Point_0.png", x = 1638, y =  584, label = "Cloister of Frost", border = false, size = POINT_SIZE, group = "Fauregandi", time = "present" },
        { file = "Point_0.png", x = 1538, y =  711, label = "Qu'Bai Arena", border = false, size = POINT_SIZE, group = "Fauregandi", time = "present" },
        { file = "Point_0.png", x = 1889, y =  886, label = "Behemoth's Dominion", border = false, size = POINT_SIZE, group = "Qufim", time = "present" },
        { file = "Point_0.png", x = 1825, y = 1036, label = "Qufim Island", border = false, size = POINT_SIZE, group = "Qufim", time = "present" },
        { file = "Point_0.png", x = 1916, y = 1024, label = "Stellar Fulcrum", border = false, size = POINT_SIZE, group = "Qufim", time = "present" },
        { file = "Point_0.png", x = 1820, y =  954, label = "Delkfutt Tower", border = false, size = POINT_SIZE, group = "Qufim", time = "present" },
        { file = "Point_0.png", x = 2278, y = 1483, label = "Maze of Shakhrami", border = false, size = POINT_SIZE, group = "Kolshushu", time = "present" },
        { file = "Point_0.png", x = 2257, y = 1640, label = "Tahrongi Canyon", border = false, size = POINT_SIZE, group = "Kolshushu", time = "present" },
        { file = "Point_0.png", x = 2487, y = 1600, label = "Buburimu Peninsula", border = false, size = POINT_SIZE, group = "Kolshushu", time = "present" },
        { file = "Point_0.png", x = 2463, y = 1753, label = "Mhaura", border = false, size = POINT_SIZE, group = "Kolshushu", time = "present" },
        { file = "Point_0.png", x = 2501, y = 1665, label = "Labyrinth of Onzozo", border = false, size = POINT_SIZE, group = "Kolshushu", time = "present" },
        { file = "Point_0.png", x = 2354, y = 1808, label = "Bibiki Bay", border = false, size = POINT_SIZE, group = "Kolshushu", time = "present" },
        { file = "Point_0.png", x =  666, y = 2014, label = "Rabao", border = false, size = POINT_SIZE, group = "Kuzotz", time = "present" },
        { file = "Point_0.png", x =  360, y = 2057, label = "Western Altepa Desert", border = false, size = POINT_SIZE, group = "Kuzotz", time = "present" },
        { file = "Point_0.png", x =  647, y = 2261, label = "Eastern Altepa Desert", border = false, size = POINT_SIZE, group = "Kuzotz", time = "present" },
        { file = "Point_0.png", x =  418, y = 2284, label = "Chamber of Oracles", border = false, size = POINT_SIZE, group = "Kuzotz", time = "present" },
        { file = "Point_0.png", x =  683, y = 2317, label = "Cloister of Tremors", border = false, size = POINT_SIZE, group = "Kuzotz", time = "present" },
        { file = "Point_0.png", x =  617, y = 2372, label = "Quicksand Caves", border = false, size = POINT_SIZE, group = "Kuzotz", time = "present" },
        { file = "Point_0.png", x = 2113, y = 1877, label = "Full Moon Fountain", border = false, size = POINT_SIZE, group = "Sarutabaruta", time = "present" },
        { file = "Point_0.png", x = 1953, y = 1762, label = "Giddeus", border = false, size = POINT_SIZE, group = "Sarutabaruta", time = "present" },
        { file = "Point_0.png", x = 1945, y = 1825, label = "Balga's Dais", border = false, size = POINT_SIZE, group = "Sarutabaruta", time = "present" },
        { file = "Point_0.png", x = 1957, y = 1871, label = "West Sarutabaruta", border = false, size = POINT_SIZE, group = "Sarutabaruta", time = "present" },
        { file = "Point_0.png", x = 2286, y = 1864, label = "East Sarutabaruta", border = false, size = POINT_SIZE, group = "Sarutabaruta", time = "present" },
        { file = "Point_0.png", x = 2224, y = 1796, label = "Outer Horutoto Ruins", border = false, size = POINT_SIZE, group = "Sarutabaruta", time = "present" },
        { file = "Point_0.png", x = 2301, y = 1944, label = "Inner Horutoto Ruins", border = false, size = POINT_SIZE, group = "Sarutabaruta", time = "present" },
        { file = "Point_0.png", x = 2196, y = 1998, label = "Toraimarai Canal", border = false, size = POINT_SIZE, group = "Sarutabaruta", time = "present" },
        { file = "Point_0.png", x =  900, y = 1468, label = "Selbina", border = false, size = POINT_SIZE, group = "Zulkheim", time = "present" },
        { file = "Point_0.png", x =  916, y = 1328, label = "Valkurm Dunes", border = false, size = POINT_SIZE, group = "Zulkheim", time = "present" },
        { file = "Point_0.png", x = 1098, y = 1276, label = "La Theine Plateau", border = false, size = POINT_SIZE, group = "Zulkheim", time = "present" },
        { file = "Point_0.png", x = 1164, y = 1472, label = "Ordelle's Caves", border = false, size = POINT_SIZE, group = "Zulkheim", time = "present" },
        { file = "Point_0.png", x = 1098, y = 1572, label = "Konschtat Highlands", border = false, size = POINT_SIZE, group = "Zulkheim", time = "present" },
        { file = "Point_0.png", x = 1182, y = 1631, label = "Gusgen Mines", border = false, size = POINT_SIZE, group = "Zulkheim", time = "present" },
        { file = "Point_0.png", x = 1318, y =  923, label = "Carpenters' Landing", border = false, size = POINT_SIZE, group = "Norvallen", time = "present" },
        { file = "Point_0.png", x = 1330, y =  854, label = "Phanauet Channel", border = false, size = POINT_SIZE, group = "Norvallen", time = "present" },
        { file = "Point_0.png", x = 1593, y = 1039, label = "Batallia Downs", border = false, size = POINT_SIZE, group = "Norvallen", time = "present" },
        { file = "Point_0.png", x = 1571, y = 1117, label = "The Eldieme Necropolis", border = false, size = POINT_SIZE, group = "Norvallen", time = "present" },
        { file = "Point_0.png", x = 1293, y = 1149, label = "Davoi", border = false, size = POINT_SIZE, group = "Norvallen", time = "present" },
        { file = "Point_0.png", x = 1292, y = 1220, label = "Monastic Cavern", border = false, size = POINT_SIZE, group = "Norvallen", time = "present" },
        { file = "Point_0.png", x = 1400, y = 1060, label = "Jugner Forest", border = false, size = POINT_SIZE, group = "Norvallen", time = "present" },
        { file = "Point_0.png", x = 2668, y = 2223, label = "Ifrit's Cauldron", border = false, size = POINT_SIZE, group = "Elshimo Uplands", time = "present" },
        { file = "Point_0.png", x = 2778, y = 2363, label = "Yhoator Jungle", border = false, size = POINT_SIZE, group = "Elshimo Uplands", time = "present" },
        { file = "Point_0.png", x = 2750, y = 2445, label = "Temple of Uggalepih", border = false, size = POINT_SIZE, group = "Elshimo Uplands", time = "present" },
        { file = "Point_0.png", x = 2763, y = 2550, label = "Cloister of Tides", border = false, size = POINT_SIZE, group = "Elshimo Uplands", time = "present" },
        { file = "Point_0.png", x = 2704, y = 2494, label = "Den of Rancor", border = false, size = POINT_SIZE, group = "Elshimo Uplands", time = "present" },
        { file = "Point_0.png", x = 2669, y = 2438, label = "Sacrificial Chamber", border = false, size = POINT_SIZE, group = "Elshimo Uplands", time = "present" },
        { file = "Point_0.png", x = 1217, y =  968, label = "East Ronfaure", border = false, size = POINT_SIZE, group = "Ronfaure", time = "present" },
        { file = "Point_0.png", x =  930, y =  969, label = "West Ronfaure", border = false, size = POINT_SIZE, group = "Ronfaure", time = "present" },
        { file = "Point_0.png", x = 1027, y = 1046, label = "Bostaunieux Oubliette", border = false, size = POINT_SIZE, group = "Ronfaure", time = "present" },
        { file = "Point_0.png", x = 1092, y = 1163, label = "King Ranperre's Tomb", border = false, size = POINT_SIZE, group = "Ronfaure", time = "present" },
        { file = "Point_0.png", x =  937, y =  827, label = "Horlais Peak", border = false, size = POINT_SIZE, group = "Ronfaure", time = "present" },
        { file = "Point_0.png", x =  940, y =  885, label = "Fort Ghelsba", border = false, size = POINT_SIZE, group = "Ronfaure", time = "present" },
        { file = "Point_0.png", x =  865, y =  827, label = "Ghelsba Outpost", border = false, size = POINT_SIZE, group = "Ronfaure", time = "present" },
        { file = "Point_0.png", x =  868, y =  884, label = "Yughott Grotto", border = false, size = POINT_SIZE, group = "Ronfaure", time = "present" },
        { file = "Point_0.png", x = 2335, y = 1128, label = "Hall of the Gods", border = false, size = POINT_SIZE, group = "Li'Telor", time = "present" },
        { file = "Point_0.png", x = 2667, y = 1415, label = "The Boyahda Tree", border = false, size = POINT_SIZE, group = "Li'Telor", time = "present" },
        { file = "Point_0.png", x = 2713, y = 1468, label = "Cloister of Storms", border = false, size = POINT_SIZE, group = "Li'Telor", time = "present" },
        { file = "Point_0.png", x = 2354, y = 1215, label = "Ro'Maeve", border = false, size = POINT_SIZE, group = "Li'Telor", time = "present" },
        { file = "Point_0.png", x = 2594, y = 1360, label = "Dragon's Aery", border = false, size = POINT_SIZE, group = "Li'Telor", time = "present" },
        { file = "Point_0.png", x = 2387, y = 1312, label = "The Sanctuary of Zi'Tah", border = false, size = POINT_SIZE, group = "Li'Telor", time = "present" },
        { file = "Point_0.png", x = 1621, y = 1687, label = "Mine Shaft 2716", border = false, size = POINT_SIZE, group = "Movalpolos", time = "present" },
        { file = "Point_0.png", x = 1572, y = 1718, label = "Newton Movalpolos", border = false, size = POINT_SIZE, group = "Movalpolos", time = "present" },
        { file = "Point_0.png", x = 1512, y = 1742, label = "Oldton Movalpolos", border = false, size = POINT_SIZE, group = "Movalpolos", time = "present" },
        { file = "Point_0.png", x = 2535, y = 2230, label = "Kazham", border = false, size = POINT_SIZE, group = "Elshimo Lowlands", time = "present" },
        { file = "Point_0.png", x = 2376, y = 2485, label = "Sea Serpent Grotto", border = false, size = POINT_SIZE, group = "Elshimo Lowlands", time = "present" },
        { file = "Point_0.png", x = 2322, y = 2481, label = "Norg", border = false, size = POINT_SIZE, group = "Elshimo Lowlands", time = "present" },
        { file = "Point_0.png", x = 2505, y = 2412, label = "Yuhtunga Jungle", border = false, size = POINT_SIZE, group = "Elshimo Lowlands", time = "present" },
        { file = "Point_0.png", x = 1068, y =  461, label = "Bearclaw Pinnacle", border = false, size = POINT_SIZE, group = "Valdeaunia", time = "present" },
        { file = "Point_0.png", x =  883, y =  511, label = "Throne Room", border = false, size = POINT_SIZE, group = "Valdeaunia", time = "present" },
        { file = "Point_0.png", x = 1070, y =  525, label = "Uleguerand Range", border = false, size = POINT_SIZE, group = "Valdeaunia", time = "present" },
        { file = "Point_0.png", x = 1116, y =  617, label = "Xarcabard", border = false, size = POINT_SIZE, group = "Valdeaunia", time = "present" },
        { file = "Point_0.png", x =  839, y =  580, label = "Castle Zvahl Keep", border = false, size = POINT_SIZE, group = "Valdeaunia", time = "present" },
        { file = "Point_0.png", x =  938, y =  609, label = "Castle Zvahl Baileys", border = false, size = POINT_SIZE, group = "Valdeaunia", time = "present" },
        { file = "Point_0.png", x =  502, y = 1417, label = "Lufaise Meadows", border = false, size = POINT_SIZE, group = "Tavnazian Archipelago", time = "present" },
        { file = "Point_0.png", x =  478, y = 1460, label = "Misareaux Coast", border = false, size = POINT_SIZE, group = "Tavnazian Archipelago", time = "present" },
        { file = "Point_0.png", x =  282, y = 1353, label = "Phomiuna Aqueducts", border = false, size = POINT_SIZE, group = "Tavnazian Archipelago", time = "present" },
        { file = "Point_0.png", x =  284, y = 1295, label = "Sacrarium", border = false, size = POINT_SIZE, group = "Tavnazian Archipelago", time = "present" },
        { file = "Point_0.png", x = 2302, y = 1395, label = "Altar Room", border = false, size = POINT_SIZE, group = "Aragoneu", time = "present" },
        { file = "Point_0.png", x = 2305, y = 1470, label = "Attohwa Chasm", border = false, size = POINT_SIZE, group = "Aragoneu", time = "present" },
        { file = "Point_0.png", x = 2292, y = 1435, label = "Boneyard Gully", border = false, size = POINT_SIZE, group = "Aragoneu", time = "present" },
        { file = "Point_0.png", x = 2308, y = 1352, label = "Castle Oztroja", border = false, size = POINT_SIZE, group = "Aragoneu", time = "present" },
        { file = "Point_0.png", x = 1901, y = 1332, label = "Garlaige Citadel", border = false, size = POINT_SIZE, group = "Aragoneu", time = "present" },
        { file = "Point_0.png", x = 2115, y = 1421, label = "Meriphataud Mountains", border = false, size = POINT_SIZE, group = "Aragoneu", time = "present" },
        { file = "Point_0.png", x = 1880, y = 1218, label = "Sauromugue Champaign", border = false, size = POINT_SIZE, group = "Aragoneu", time = "present" },
        { file = "Point_0.png", x = 2026, y =  653, label = "Celestial Nexus", border = false, size = POINT_SIZE, group = "Tu'Lia", time = "present" },
        { file = "Point_0.png", x = 2027, y =  699, label = "La'Loff Amphitheater", border = false, size = POINT_SIZE, group = "Tu'Lia", time = "present" },
        { file = "Point_0.png", x = 2029, y =  897, label = "Ru'Aun Gardens", border = false, size = POINT_SIZE, group = "Tu'Lia", time = "present" },
        { file = "Point_0.png", x = 2028, y =  743, label = "The Shrine of Ru'Avitau", border = false, size = POINT_SIZE, group = "Tu'Lia", time = "present" },
        { file = "Point_0.png", x = 2029, y =  841, label = "Ve'Lugannon Palace", border = false, size = POINT_SIZE, group = "Tu'Lia", time = "present" },
        { file = "Point_0.png", x = 4586, y = 1842, label = "Al Zahbi", border = false, size = POINT_SIZE, group = "West Aht Urhgan", time = "present" },
        { file = "Point_0.png", x = 4764, y = 1865, label = "Aht Urhgan Whitegate", border = false, size = POINT_SIZE, group = "West Aht Urhgan", time = "present" },
        { file = "Point_0.png", x = 4589, y = 1642, label = "Bhaflau Thickets", border = false, size = POINT_SIZE, group = "West Aht Urhgan", time = "present" },
        { file = "Point_0.png", x = 4584, y = 2007, label = "Wajaom Woodlands", border = false, size = POINT_SIZE, group = "Mamool Ja Savagelands", time = "present" },
        { file = "Point_0.png", x = 3853, y =  737, label = "Arrapago Reef", border = false, size = POINT_SIZE, group = "Arrapago Islands", time = "present" },
        { file = "Point_0.png", x = 3588, y =  843, label = "Periqia", border = false, size = POINT_SIZE, group = "Arrapago Islands", time = "present" },
        { file = "Point_0.png", x = 3801, y =  944, label = "Talacca Cove", border = false, size = POINT_SIZE, group = "Arrapago Islands", time = "present" },
        { file = "Point_0.png", x = 3803, y = 1006, label = "Hazhalm Testing Grounds", border = false, size = POINT_SIZE, group = "Arrapago Islands", time = "present" },
        { file = "Point_0.png", x = 4141, y = 1007, label = "Leujaoam Sanctum", border = false, size = POINT_SIZE, group = "Arrapago Islands", time = "present" },
        { file = "Point_0.png", x = 3970, y = 1075, label = "Nashmau", border = false, size = POINT_SIZE, group = "Arrapago Islands", time = "present" },
        { file = "Point_0.png", x = 4100, y =  866, label = "Caedarva Mire", border = false, size = POINT_SIZE, group = "Arrapago Islands", time = "present" },
        { file = "Point_0.png", x = 3589, y = 1191, label = "Arrapago Remnants", border = false, size = POINT_SIZE, group = "Ruins of Alzadaal", time = "present" },
        { file = "Point_0.png", x = 4059, y = 1347, label = "Nyzul Isle", border = false, size = POINT_SIZE, group = "Ruins of Alzadaal", time = "present" },
        { file = "Point_0.png", x = 4061, y = 1443, label = "Alzadaal Undersea Ruins", border = false, size = POINT_SIZE, group = "Ruins of Alzadaal", time = "present" },
        { file = "Point_0.png", x = 4737, y = 1373, label = "Bhaflau Remnants", border = false, size = POINT_SIZE, group = "Ruins of Alzadaal", time = "present" },
        { file = "Point_0.png", x = 4157, y = 1911, label = "Halvung", border = false, size = POINT_SIZE, group = "Halvung Territory", time = "present" },
        { file = "Point_0.png", x = 3882, y = 1790, label = "Navukgo Execution Chamber", border = false, size = POINT_SIZE, group = "Halvung Territory", time = "present" },
        { file = "Point_0.png", x = 4121, y = 1780, label = "Mount Zhayolm", border = false, size = POINT_SIZE, group = "Halvung Territory", time = "present" },
        { file = "Point_0.png", x = 4303, y = 1709, label = "Lebros Cavern", border = false, size = POINT_SIZE, group = "Halvung Territory", time = "present" },
        { file = "Point_0.png", x = 4013, y = 2254, label = "Jade Sepulcher", border = false, size = POINT_SIZE, group = "Mamool Ja Savagelands", time = "present" },
        { file = "Point_0.png", x = 3972, y = 2476, label = "Mamool Ja Training Grounds", border = false, size = POINT_SIZE, group = "Mamool Ja Savagelands", time = "present" },
        { file = "Point_0.png", x = 4169, y = 2345, label = "Mamook", border = false, size = POINT_SIZE, group = "Mamool Ja Savagelands", time = "present" },
        { file = "Point_0.png", x = 4374, y = 2128, label = "Aydeewa Subterrane", border = false, size = POINT_SIZE, group = "Mamool Ja Savagelands", time = "present" },
        { file = "Point_0.png", x = 1339, y = 1951, label = "Bastok Mines", border = false, size = POINT_SIZE, group = "Bastok", time = "present" },
        { file = "Point_0.png", x = 1249, y = 1909, label = "Bastok Markets", border = false, size = POINT_SIZE, group = "Bastok", time = "present" },
        { file = "Point_0.png", x = 1341, y = 1884, label = "Metalworks", border = false, size = POINT_SIZE, group = "Bastok", time = "present" },
        { file = "Point_0.png", x = 1339, y = 1819, label = "Port Bastok", border = false, size = POINT_SIZE, group = "Bastok", time = "present" },
        { file = "Point_0.png", x = 1072, y = 1001, label = "Southern San d'Oria", border = false, size = POINT_SIZE, group = "San d'Oria", time = "present" },
        { file = "Point_0.png", x = 1073, y =  948, label = "Northern San d'Oria", border = false, size = POINT_SIZE, group = "San d'Oria", time = "present" },
        { file = "Point_0.png", x = 1045, y =  909, label = "Port San d'Oria", border = false, size = POINT_SIZE, group = "San d'Oria", time = "present" },
        { file = "Point_0.png", x = 1097, y =  916, label = "Chateau d'Oraguille", border = false, size = POINT_SIZE, group = "San d'Oria", time = "present" },
        { file = "Point_0.png", x = 2085, y = 1997, label = "Port Windurst", border = false, size = POINT_SIZE, group = "Windurst", time = "present" },
        { file = "Point_0.png", x = 2132, y = 1967, label = "Windurst Walls", border = false, size = POINT_SIZE, group = "Windurst", time = "present" },
        { file = "Point_0.png", x = 2136, y = 2007, label = "Windurst Woods", border = false, size = POINT_SIZE, group = "Windurst", time = "present" },
        { file = "Point_0.png", x = 2085, y = 1955, label = "South Windurst Waters", border = false, size = POINT_SIZE, group = "Windurst", time = "present" },
        { file = "Point_0.png", x = 2092, y = 1925, label = "North Windurst Waters", border = false, size = POINT_SIZE, group = "Windurst", time = "present" },
        { file = "Point_0.png", x = 1773, y = 1219, label = "Port Jeuno", border = false, size = POINT_SIZE, group = "Jeuno", time = "present" },
        { file = "Point_0.png", x = 1716, y = 1249, label = "Lower Jeuno", border = false, size = POINT_SIZE, group = "Jeuno", time = "present" },
        { file = "Point_0.png", x = 1704, y = 1178, label = "Upper Jeuno", border = false, size = POINT_SIZE, group = "Jeuno", time = "present" },
        { file = "Point_0.png", x = 1733, y = 1210, label = "Ru'Lude Gardens", border = false, size = POINT_SIZE, group = "Jeuno", time = "present" },
        { file = "Point_0.png", x = 2588, y = 2448, label = "West Sarutabaruta [S]", border = false, size = POINT_SIZE, group = "The Sarutabaruta Front", time = "past" },
        { file = "Point_0.png", x = 2655, y = 2688, label = "Windurst Waters [S]", border = false, size = POINT_SIZE, group = "Windurst", time = "past" },
        { file = "Point_0.png", x = 2746, y = 2194, label = "Fort Karugo-Narugo [S]", border = false, size = POINT_SIZE, group = "The Sarutabaruta Front", time = "past" },
        { file = "Point_0.png", x = 3081, y = 1868, label = "Castle Oztroja [S]", border = false, size = POINT_SIZE, group = "The Aragoneu Front", time = "past" },
        { file = "Point_0.png", x = 2823, y = 1879, label = "Meriphataud Mountains [S]", border = false, size = POINT_SIZE, group = "The Aragoneu Front", time = "past" },
        { file = "Point_0.png", x = 2558, y = 1785, label = "Garlaige Citadel [S]", border = false, size = POINT_SIZE, group = "The Aragoneu Front", time = "past" },
        { file = "Point_0.png", x = 2542, y = 1651, label = "Sauromugue Champaign [S]", border = false, size = POINT_SIZE, group = "The Aragoneu Front", time = "past" },
        { file = "Point_0.png", x = 2021, y = 1627, label = "Vunkerl Inlet [S]", border = false, size = POINT_SIZE, group = "The Derfland Front", time = "past" },
        { file = "Point_0.png", x = 2042, y = 1495, label = "The Eldieme Necropolis [S]", border = false, size = POINT_SIZE, group = "The Norvallen Front", time = "past" },
        { file = "Point_0.png", x = 2130, y = 1759, label = "Rolanberry Fields [S]", border = false, size = POINT_SIZE, group = "The Derfland Front", time = "past" },
        { file = "Point_0.png", x = 2048, y = 1901, label = "Crawlers' Nest [S]", border = false, size = POINT_SIZE, group = "The Derfland Front", time = "past" },
        { file = "Point_0.png", x = 1760, y = 1705, label = "La Vaule [S]", border = false, size = POINT_SIZE, group = "The Norvallen Front", time = "past" },
        { file = "Point_0.png", x = 1809, y = 1492, label = "Jugner Forest [S]", border = false, size = POINT_SIZE, group = "The Norvallen Front", time = "past" },
        { file = "Point_0.png", x = 1918, y = 1424, label = "The Norvallen Front", border = false, size = POINT_SIZE, group = "Regions", time = "past" },
        { file = "Point_0.png", x = 1985, y = 1379, label = "Batallia Downs [S]", border = false, size = POINT_SIZE, group = "The Norvallen Front", time = "past" },
        { file = "Point_0.png", x = 2824, y = 1758, label = "The Aragoneu Front", border = false, size = POINT_SIZE, group = "Regions", time = "past" },
        { file = "Point_0.png", x =  450, y = 1425, label = "Tavnazian Safehold", border = false, size = POINT_SIZE, group = "Tavnazian Archipelago", time = "present" },
        { file = "Point_0.png", x = 1620, y = 2560, label = "Bastok Markets [S]", border = false, size = POINT_SIZE, group = "Bastok", time = "past" },
        { file = "Point_0.png", x = 1588, y = 2436, label = "The Gustaberg Front", border = false, size = POINT_SIZE, group = "Regions", time = "past" },
        { file = "Point_0.png", x = 1592, y = 2130, label = "Grauberg [S]", border = false, size = POINT_SIZE, group = "The Gustaberg Front", time = "past" },
        { file = "Point_0.png", x = 1306, y = 2352, label = "North Gustaberg [S]", border = false, size = POINT_SIZE, group = "The Gustaberg Front", time = "past" },
        { file = "Point_0.png", x = 2845, y = 2411, label = "The Sarutabaruta Front", border = false, size = POINT_SIZE, group = "Regions", time = "past" },
        { file = "Point_0.png", x = 1878, y = 2051, label = "Beadeaux [S]", border = false, size = POINT_SIZE, group = "The Derfland Front", time = "past" },
        { file = "Point_0.png", x = 1706, y = 1911, label = "Pashhow Marshlands [S]", border = false, size = POINT_SIZE, group = "The Derfland Front", time = "past" },
        { file = "Point_0.png", x = 1843, y = 1880, label = "The Derfland Front", border = false, size = POINT_SIZE, group = "Regions", time = "past" },
        { file = "Point_0.png", x = 1489, y =  883, label = "The Valdeaunia Front", border = false, size = POINT_SIZE, group = "Regions", time = "past" },
        { file = "Point_0.png", x = 1518, y =  855, label = "Xarcabard [S]", border = false, size = POINT_SIZE, group = "The Valdeaunia Front", time = "past" },
        { file = "Point_0.png", x = 1099, y =  733, label = "Throne Room [S]", border = false, size = POINT_SIZE, group = "The Valdeaunia Front", time = "past" },
        { file = "Point_0.png", x = 1095, y =  808, label = "Castle Zvahl Keep [S]", border = false, size = POINT_SIZE, group = "The Valdeaunia Front", time = "past" },
        { file = "Point_0.png", x = 1224, y =  826, label = "Castle Zvahl Baileys [S]", border = false, size = POINT_SIZE, group = "The Valdeaunia Front", time = "past" },
        { file = "Point_0.png", x = 1926, y = 1058, label = "The Fauregandi Front", border = false, size = POINT_SIZE, group = "Regions", time = "past" },
        { file = "Point_0.png", x = 1875, y =  941, label = "Beaucedine Glacier [S]", border = false, size = POINT_SIZE, group = "The Fauregandi Front", time = "past" },
        { file = "Point_0.png", x = 1457, y = 1452, label = "The Ronfaure Front", border = false, size = POINT_SIZE, group = "Regions", time = "past" },
        { file = "Point_0.png", x = 1554, y = 1324, label = "East Ronfaure [S]", border = false, size = POINT_SIZE, group = "The Ronfaure Front", time = "past" },
        { file = "Point_0.png", x = 1276, y = 1333, label = "Southern San d'Oria [S]", border = false, size = POINT_SIZE, group = "San d'Oria", time = "past" },
        { file = "Point_0.png", x = 2583, y =  514, label = "Lumoria", border = false, size = POINT_SIZE, group = "Regions", time = "present" },
        { file = "Point_0.png", x = 2576, y =  494, label = "Grand Palace of Hu'Xzoi", border = false, size = POINT_SIZE, group = "Lumoria", time = "present" },
        { file = "Point_0.png", x = 2576, y =  541, label = "Al'Taieu", border = false, size = POINT_SIZE, group = "Lumoria", time = "present" },
        { file = "Point_0.png", x = 2576, y =  449, label = "The Garden of Ru'Hmet", border = false, size = POINT_SIZE, group = "Lumoria", time = "present" },
        { file = "Point_0.png", x =  375, y = 1558, label = "Sealions Den", border = false, size = POINT_SIZE, group = "Tavnazian Archipelago", time = "present" },
        { file = "Point_0.png", x =  236, y = 1221, label = "Riverne - Site A01", border = false, size = POINT_SIZE, group = "Tavnazian Archipelago", time = "present" },
        { file = "Point_0.png", x =  236, y = 1134, label = "Riverne - Site B01", border = false, size = POINT_SIZE, group = "Tavnazian Archipelago", time = "present" },
        { file = "Point_0.png", x =  173, y = 1174, label = "Monarch Linn", border = false, size = POINT_SIZE, group = "Tavnazian Archipelago", time = "present" },
    },
};
